### ISSUE TITLE
DANDI landing page

### ISSUE THREAD

**Issue by satra** [dandi/dandi.github.io#1]
- on github to start
- link to neurostars tags
- provide roadmap for Year 1

**Comment by yarikoptic** [comment]
Do you have one in mind from existing ones to take as a starting point?  no webdesign skills here ;-)

**Comment by bendichter** [comment]
I'd like to set up a few things services that are relevant to the landing page:

1) Include a sign-up to a DANDI newsletter to inform users of new developments, solicit the field for datasets, get the word out about hackathons, etc. I've used MailChimp, which I like (free).
2) Set up google analytics on the website to see what type of activity we are getting (free).
3) Set up an email for questions. Would it be possible to set up contact@dandiarchive.org? Second choice would be dandi.archive@mit.edu, third would be dandi.archive@gmail.com.
4) Set up a twitter account for DANDI (maybe a little premature).
5) To make these services easier to access, I'd also like to create a LastPass group that holds the credentials for these services. Then I'd add you three to that group so we can all easily access these and other services.

Thoughts on these?

**Comment by bendichter** [comment]
Also as for design I could talk to the guy who designed [the NWB newsletter](https://mailchi.mp/49a33d0ef48e/nwbn-newsletter-aug-2019?e=[UNIQID]) for us

**Comment by yarikoptic** [comment]
`5`. Good idea - go ahead. Never used it though
`4`. We do have https://twitter.com/dandiarchive already
`3`. @satra would know more about emails setups we could do with the least of sweat. May be a few more mailman lists would be sufficient for announcements and support
`2`. Google analytics is a thorny topic. Eventually we will enable it or some other js beast. If we hosted it, could just analyze http logs.

**Comment by yarikoptic** [comment]
> Also as for design I could talk to the guy who designed [the NWB newsletter](https://mailchi.mp/49a33d0ef48e/nwbn-newsletter-aug-2019?e=%5BUNIQID%5D) for us

I don't mind any assistance on design ;-)

**Comment by bendichter** [comment]
Why is Google analytics thorny?

**Comment by yarikoptic** [comment]
> Why is Google analytics thorny?

Many people don't appreciate being tracked beyond obvious. Whenever I can I do disable Google analytics js which allows Google to track me on non Google sites

**Comment by bendichter** [comment]
@yarikoptic Hmm ok I usually expect people to use incognito mode if they don't want to be tracked and expect to be tracked otherwise, but I can see how that would get us off on the wrong foot with some of our more tech savvy users. Is there a way to gather this type of data without selling our souls to Google?

let's put links to our slack channel and twitter on the landing page

**Comment by satra** [comment]
if you like the general layout of [my group's page](https://satra.cogitatum.org/group), it's a jekyll based responsive static site generator and can be tuned pretty well. the nice thing about this is that it would support blogs and other features as well.

it also uses data files, which means we should be able to transform to other technologies in the future without losing info.

**Comment by mgrauer** [comment]
We could also make use of Jared Tomeck@Kitware for design, he did the Dandi
logo and UI screenshots for the proposal. He also does website design and
has worked with Jekyll before. We probably couldn't do this before
mid-September though--but that gives some time to gather content, and I
expect keeping the website looking fresh will be an ongoing project.

**Comment by yarikoptic** [comment]
I think this sounds like the best plan to go forward indeed.
So should we
- initiate `dandi/dandiproject.org`  repository with a really basic single page having logo, contact info, and "Under construction" (I can do that ;))
- populate a few files (not visible online) with content we would like to see available
- ask Jared to make it into a website

**Comment by satra** [comment]
@bendichter - info@dandiarchive.org is now active - for discussions and announcements, i would simply use neurostars.org

@yarikoptic - i'll push a barebones version of jekyll to dandi.github.io

**Comment by satra** [comment]
@yarikoptic and others. basic version pushed. please add your details to `_data/team_members.yml`

**Comment by satra** [comment]
ok certificate errors are now resolved and site is available at: https://dandiarchive.org/

**Comment by yarikoptic** [comment]
Great, thank you @satra! I will fill out the details whenever get to the laptop
