### ISSUE TITLE
Add slack information to the website(s)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi.github.io#23]
BTW, when I go to e.g. https://dandiarchive.slack.com/archives/CMGDETALC I see at the bottom:

```
If you have an @alleninstitute.org email address, you can create an account.
```

Does it mean that we are somehow restricting access or require individual invitation to join the slack channel.

**Comment by satra** [comment]
they can join with the invitation i posted in the workflow, but in the early days i simply added allen as a default since there were several folks there. i'll change the allen thing and make everyone use the public invitation.

**Comment by satra** [comment]
will be taken care of in #25

**Comment by yarikoptic** [comment]
uff... ok - I will try to locate that workflow document again to dig out the invitation ... #25 is still open, and seems to be a "bigger" item.  Would be nice to resolve this particular aspect (adding slack information so it could be found) independently

**Comment by satra** [comment]
there is no link possibility to slack any more. i need to add people manually. i do that whenever they join the archive. the workflow document here has been updated. is it ok if i now add this workflow to the www.... website?
https://docs.google.com/document/d/1ehxd5a6Hurz7VqQDAszEpGASRTUP6muXYwJ5wgXhzU4/edit

**Comment by yarikoptic** [comment]
I do not mind it (workflow) being public!  if not website -- could be https://github.com/dandi/dandi-cli/#preparing-and-uploading-a-dandiset-to-dandiarchiveorg . If website -- we need to change dandi-cli's README.md to point to it instead.

**Comment by yarikoptic** [comment]
so, re adding @jwodder to slack, John please first register on https://gui.dandiarchive.org/ .

**Comment by satra** [comment]
it is public. but we have no reference to how to interact with the archive anywhere. we need to come up with a page describing that.  so having a page we can point to would be useful. we can point to the google doc, but doesn't look very professional.

Effectively we need a place that lists these things

```
> How to download data

> Create dataset 

> Upload data

> Standards supported

> Create NWB files
```

**Comment by yarikoptic** [comment]
Ideally we should initiate something like http://handbook.datalad.org  (either based on it - .rst, or remake of bids-specification).   I have found the initial steps to start based on datalad's one, and now pushed as a PR here : https://github.com/dandi/handbook-temp/pull/1 .  Not sure yet what to fixup to have it built and what else to remove.  But it could be actually near the completion to start filling it up after lobotomizing it more ;)

Meanwhile - majority of those (besides "Create NWB files") are largely in purview of dandi-cli, so IMHO the best spot would be its README. (which it already does, just needs tune up).   http://handbook.dandiarchive.org could even be initiated and just redirect to that README.

**Comment by satra** [comment]
i think it should be on the website somewhere. only upload data is in the cli. there are other things like adding collaborators, etc.,.

**Comment by jwodder** [comment]
@yarikoptic I have registered using my GitHub account.
