### ISSUE TITLE
Link to the newsletter is broken

### ISSUE THREAD

**Issue by TomDonoghue** [dandi/dandi.github.io#49]
On the `https://www.dandiarchive.org/` homepage, there is a link to join a newsletter. 

This link goes to: https://mailchi.mp/7c90915cdcc3/dandi-newsletter-signup
Which seems to be a broken link / gives a page not found error.

**Comment by yarikoptic** [comment]
Sorry @TomDonoghue it tooks us that long.  It was removed/replaced in 41c9e2244a6f64f98e3d6fe7f4898f2e8f457f91 so we are all good for a while ;)
